### ISSUE TITLE
Including col-sidebar from a subdir?

### ISSUE THREAD

**Issue by drwetter** [OWASP/www--site-theme#14]
Hi,

I wanted to include the sidebar on subdirectories, see https://github.com/OWASP/www-chapter-germany/tree/master/stammtische but neither ``layout: col-sidebar`` nor ``layout: ../col-sidebar`` works and returns:

```
The page build failed for the `master` branch with the following error:

A file was included in `/_layouts/col-sidebar.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#file-is-a-symlink.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

Dirk

**Comment by hblankenship** [comment]
It wasn't the sidebar that was the issue.  It was the missing leaders.md file (must include both info.md and leaders.md).  I believe I fixed this for you.

**Comment by greenhill-owasp** [comment]
Hi,

It seems that we're receiving the same error as above. We have all required files. Do you know what our issue is?

https://github.com/OWASP/www-chapter-toronto/tree/master/

Thanks,
Adam
