### ISSUE TITLE
any feasibility of oembedding links

### ISSUE THREAD

**Issue by anantshri** [OWASP/www--site-theme#16]
jekyll supports third party plugins which may allow us to oembed meetup or other links.

I am right now doing it manually and take some manual efforts to update. If we can have custom plugins that would save a lot of hassles. 

Possible challenges:
if we use a custom plugin then the github jekyll builds cant be used as they dont support custom plugin and we will have to look for build alternatives. 

Thinks that could be oembedded
- meetup
- slideshare
- speakerdeck
- and many other sites supported oembed

**Comment by anantshri** [comment]
updated issues to be more generic

**Comment by bkimminich** [comment]
Sound all like legit and useful extras, but before the basic setup works reliably we might not want to add more moving parts to the machinery. I've thrown this as a general question into https://owasp.slack.com/archives/CQC4SEZ3N/p1573510761021000 for discussion.

**Comment by kingthorin** [comment]
It's been like 6mo, could we get an answer on this?

**Comment by hblankenship** [comment]
We are currently sticking with github builds in the foreseeable future but would be open to seeing work done on altering the build to use a good CI/CD stack (then we could also implement better testing).
