### ISSUE TITLE
can we not mess around with master theme if its linked to all projects

### ISSUE THREAD

**Issue by anantshri** [OWASP/www--site-theme#17]
can we not mess around with master theme atleast the master node of it as its linked with all projects. currently it has rendered all the pages in a not so good state. sidebars are all gone below the text.

Current render due to theme errors

![owasp_bhopal_defunc_render](https://user-images.githubusercontent.com/236843/68616135-6e715180-04ea-11ea-8b42-8bbe18b54c60.jpg)

What it should be

![OWASP_bhopal_should_be_render](https://user-images.githubusercontent.com/236843/68616136-6f09e800-04ea-11ea-8842-f1f74f4f8494.png)

**Comment by bkimminich** [comment]
Looks a lot like a messed-up version of the small-screen layout to me... On my laptop the page looks fine and when I reduce window size goes into smal-screen layout which also looks okay (except for the custom grey box not honoring padding)

![image](https://user-images.githubusercontent.com/3531020/68625389-4deccb80-04d9-11ea-8cd4-d20a81baa137.png)

**Comment by anantshri** [comment]
this mess was made due to changes done on master theme as this theme is live referred by every subsite any changes in master are immediately reflected in the other sites.

later commit assuming https://github.com/OWASP/www--site-theme/commit/66d7626e25fc5bd32d47ddc6886953a5adf38f7d  fixed the layout back to normal.
