### ISSUE TITLE
Projects navbar menu

### ISSUE THREAD

**Issue by bkimminich** [OWASP/www--site-theme#19]
The _Projects_ menu show a static (?) and mostly nonsensical selection of projects right now. Some links are not even projects. This might be temporarily replaced with a static list of flagships until there is a dynamic solution based on a) site visits or b) GitHub stars (on the project repo, not the page repo). Maybe even submenus for _Tools_, _Code_ and _Documentation_ would make sense?

![image](https://user-images.githubusercontent.com/3531020/69195873-2aef9680-0b2d-11ea-82ea-e3bb2f4ac330.png)

**Comment by hblankenship** [comment]
Well, it isn't nonsensical, per se.  Those are the top pages from Google Analytics on the old wiki.  I agree that some of them aren't projects and I pointed that out as well (though they are related to the cheatsheets project).  I would rather have just projects here and have something else (new menu) for community pages (csrf, xss).  I'll bring it up again.

**Comment by bkimminich** [comment]
So, filtering those for projects only would be a possible workaround...?

**Comment by mikemccamon** [comment]
Updated to Flagship projects that have migrated to website.
