### ISSUE TITLE
Menuitem with external link

### ISSUE THREAD

**Issue by mikemccamon** [OWASP/www--site-theme#21]
We need to add a parameter for our menu.json file that will load the link in a new window i.e.  target="_blank" 

So our parameter could be 
target: external

If target = external, append  target="_blank"  to link

**Comment by anantshri** [comment]
Ensure rel=noopener is also added if we are adding target=_blank anywhere.

Our own reference

https://www.owasp.org/index.php/Reverse_Tabnabbing

**Comment by hblankenship** [comment]
These are both in.  Use "opentab" : "true" for opening a new tab (target blank).
