### ISSUE TITLE
Add News/Events to all templates

### ISSUE THREAD

**Issue by mikemccamon** [OWASP/www--site-theme#22]
Can we just include news-events.html into sidebars? It would be good to get news and our major events distributed to all the pages on the site

**Comment by hblankenship** [comment]
Removing until we get support for this type of thing from Github

**Comment by bkimminich** [comment]
Please do not eat up even more space on sidenavs... They're cramped enough already with the project/chapter specific links, leaders, category icons, foundation elevator pitch etc.

**Comment by mikemccamon** [comment]
I can just hard code the News into theme until we have a new solution

====================
Mike McCamon
Executive Director, OWASP
913.940.2737
Sent while mobile so please excuse typos

**Comment by hblankenship** [comment]
events were added at the bottom of the sidenav some time ago.
