### ISSUE TITLE
style change to reflect tabs are tabs and not just text

### ISSUE THREAD

**Issue by anantshri** [OWASP/www--site-theme#25]
Current style does nothing to specifically mark out tabs as tabs. can we get a better button style css to cover that out as clickable entity.

**Comment by hblankenship** [comment]
added this.  we can discuss asthetics.

**Comment by bkimminich** [comment]
Please close issues that have been addressed/fixed/implemented sooner. Thanks!

**Comment by hblankenship** [comment]
I was allowing for time to discuss but agreed to close and a new issue can be opened if not sufficient.
