### ISSUE TITLE
Tab-clicks let viewport jump downwards

### ISSUE THREAD

**Issue by bkimminich** [OWASP/www--site-theme#30]
Example: https://www2.owasp.org/www-project-juice-shop/#div-ctf

Clicks scroll viewport down to the headline, so that the tabs and navbar are out of sight. You need to scroll back up to navigate to another tab. This is highly annoying for user experience.

(Experienced on Google Chrome on Chrome OS)

**Comment by kingthorin** [comment]
Same with IE and Firefox on Win7 as well as Firefox and Chrome on Win 10.

**Comment by hblankenship** [comment]
This should be resolved now

**Comment by kingthorin** [comment]
Agreed, it does seem fixed.
