### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by drwetter** [OWASP/www--site-theme#31]
.. is IMO too large.

**Comment by hblankenship** [comment]
The font was changed for readability.  Current size is the expected size going forward.

**Comment by drwetter** [comment]
> The font was changed for readability.

So 98% of all other visited web sites around have readability problems, too?

It looks to me a bit like for elderly people who refuse to wear glasses -- I am not kidding, just telling how it looks to me (using 1k to 2k resolutions from small 14'' laptop screen to a 27'' monitor with a viewing distance of 60+ cm (2 ft). )
