### ISSUE TITLE
Image size?

### ISSUE THREAD

**Issue by drwetter** [OWASP/www--site-theme#34]
... is there any way to achieve this?

**Comment by hblankenship** [comment]
Did you include a screenshot or something?  I don't see anything referenced.

**Comment by hblankenship** [comment]
Perhaps you are referencing image size in Markdown.  And, while it won't show correctly on the markdown file, it gets correctly rendered to the website:

![Text](link to some image){:width="65px"}

**Comment by drwetter** [comment]
Thanks. In the meantime I had success with 

```
{:refdef: style="width: 20px; height: 20px"}
![Incubator Project](/assets/images/common/owasp_level_incubator.svg)
{: refdef}
```
