### ISSUE TITLE
Uglyness of spacing

### ISSUE THREAD

**Issue by drwetter** [OWASP/www--site-theme#35]
Hi,

as of now the result looks pretty much like a page in Markdown and not a page in HTML.  This is IMO not appropriate for a modern web site.  The most disturbing issue to the eyes is the spacing between headlines and subsequent text.

![Screenshot_20191219_094712](https://user-images.githubusercontent.com/8036727/71158647-97e96f80-2244-11ea-9139-0fadb41c1055.png)

The headlines have the same spacing as to the text below as to above. Worse, some times it looks like the spacing of the headline to its paragraph is bigger.

Suggestion: Provide a proper style property (CSS) which has smaller space to below and keep the space to above. At the moment there's no style for ``h2`` or ``h3``.

**Comment by hblankenship** [comment]
h2, h3, h4 all have styles....is this specific to mobile?  I'll look there.

**Comment by drwetter** [comment]
Nope, that was taken from https://www2.owasp.org/www-project-docker-top-10/. To be precise: If I look at the debugger I see a style:

```
h1, h2, h3, h4, h5, h6, strong {
    font-family: 'titillium', sans-serif;
    font-weight: bold;
}
```

But not something which I meant.

**Comment by drwetter** [comment]
and there's a style for the side bar which nullifies all margins. Likely we want instead to set them?

**Comment by hblankenship** [comment]
In the info.md file, you can use * lists to remove spacing:
* item1
* item2
* item3

The list is shown without decoration.

**Comment by drwetter** [comment]
Harold,

What? please reopen.

I don't want bullet lists. As mentioned I want the headline on the sidebar (and on the main page) to have proper spacing. It has now the same distance to above as to below.

It looks rotten ugly and definitely not like we should present this to a visitor. 

Thanks, Dirk
