### ISSUE TITLE
Control of linefeeds?

### ISSUE THREAD

**Issue by drwetter** [OWASP/www--site-theme#36]
Hi,

this seems to be a matter of Markdown. However when I provide a web page I would like to have control over line feeds and not rely purely on the capabilities of Markdown. We wanted to host HTML, not MD, right?

It would help if one
* could enforce a single line feed
* could prevent line feeds when normally md will insert such

**Comment by drwetter** [comment]
okay, enforcing a lf works by supplying ``<br />``

**Comment by hblankenship** [comment]
Hey, Dirk, you can also you straight HTML if you are comfortable with it.

**Comment by drwetter** [comment]
Thanks, Harold. For me no problem. 

For preventing a line feed the only option would be then just use HTML for that context?

**Comment by hblankenship** [comment]
Depending on the context but, generally, yes.
