### ISSUE TITLE
Header hard coded link to www2

### ISSUE THREAD

**Issue by mikemccamon** [OWASP/www--site-theme#37]
Please update header.html at launch . Line 37 hard codes a link to https://www2.owas...

**Comment by hblankenship** [comment]
Explain? https://www2.owasp.com is hard-coded in many places.

**Comment by drwetter** [comment]
Hardcoding takes places everywhere! 

For www2. this is a nobrainer. As you can keep the DNS record for a while.
 
But people link to the old site. It's EVERYWHERE!

Links should be relative and not absolute. See discussion @ slack. Looking at it I believe there's still a lot of work needed before really switching the sites.

**Comment by hblankenship** [comment]
This was removed in the header
