### ISSUE TITLE
Proper link for uploads dir?

### ISSUE THREAD

**Issue by drwetter** [OWASP/www--site-theme#38]
Hi,

maybe I missed that but I haven't found an announcement where to look for the uploads. 

The search function then revealed a desktop.ini @ https://github.com/OWASP/www-community/blob/743f444f33df7305d93a36454b7b3ff70e94ee6e/assets/files/migrated/desktop.ini .

We would need an official statement where I can link to. Sorry if I missed that. 

BTW: We have in Germany hundreds of local meetings where we link to the slides. That's some amount of work to correctly link to those. We haven't even started with providing the (HTML)  content. So we aren't even close to switch sites. But it's not only that why I think we should give this more time.

Cheers, Dirk

**Comment by hblankenship** [comment]
If you mean asset files which your chapter links to, you can put them in your assets/files directory or similar under your repository.

**Comment by drwetter** [comment]
You aren't really indicating that I am supposed to copy hundreds of files???

I just want to link to them

**Comment by hblankenship** [comment]
All pdf content are located in www-pdf-archive.  You can link to that directory.  For instance:

https://www2.owasp.org/www-pdf-archive/10_security_trends.pdf

If you mean commonly used images those are typically under /assets/images or /assets/images/common, depending on the repository (owasp.github.io or www--site-theme).

**Comment by drwetter** [comment]
Ok, one step forward. But this needs A LOT OF WORK if we're doing it manually.

Examples for 50+ Slides:

* https://www.owasp.org/index.php/OWASP_German_Chapter_Stammtisch_Initiative/M%C3%BCnchen
* https://www.owasp.org/index.php/OWASP_German_Chapter_Stammtisch_Initiative/Hamburg
* https://www.owasp.org/index.php/OWASP_AppSec_Research_2010_-_Stockholm,_Sweden (Don't know why this page looks so weird).

Please advise.

**Comment by bkimminich** [comment]
If running e.G.  https://www.owasp.org/index.php/OWASP_German_Chapter_Stammtisch_Initiative/Hamburg through Harold's automatic converter then we should at least have markdown. If the file names stay as they were, shouldn't it be down to a Search& ReplaceAll with the new base URL for the files? Externally linked slides or MeetUp event pages etc. should be fine anyway.

**Comment by drwetter** [comment]
That came later also into my mind :-)

We would need then to distribute the script or have that done by the automatic converter (and rerun it).

The latter approach would also help for unmaintained pages. For the project pages I don't feel much sorry but for former conference pages it would be a loss.



-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by hblankenship** [comment]
currently working on a solution to update the links in the already auto-migrated content in migrated_content.md in some (most) repos.  After that I will run it against the markdown files in https://github.com/OWASP-Foundation/owasp-wiki-md/  This only updates pdf links and not image links, etc.

**Comment by cw-owasp** [comment]
> All pdf content are located in www-pdf-archive. You can link to that directory. For instance:
> 
> https://www2.owasp.org/www-pdf-archive/10_security_trends.pdf
> 
> If you mean commonly used images those are typically under /assets/images or /assets/images/common, depending on the repository (owasp.github.io or www--site-theme).

This pile of files doesn’t help people find the current version of the files.

**Comment by cw-owasp** [comment]
I asked a similar question on the leaders mailing list, and maybe also on the Slack channel but didn’t get an answer before the site launch deadline, or since. So I put each set of Media Wiki files in a separate (language named subdirectory) with all the previous versions, adding the version number into each filename, and a changelog.txt file for the data that Media Wiki used to display.

For example:

https://github.com/OWASP/www-project-automated-threats-to-web-applications/tree/master/assets/files/EN

https://github.com/OWASP/www-project-cornucopia/tree/master/assets/files/ecommerce/EN

https://github.com/OWASP/www-project-snakes-and-ladders/tree/master/assets/files/web/ZH

I then link to the folder from pages, rather than an individual file.

Not sure if this was okay, but there was no guidance.
