### ISSUE TITLE
Use badges from shields.io for 'Builders/Breakers/Defenders'

### ISSUE THREAD

**Issue by fzipi** [OWASP/www--site-theme#43]
Can't we use badges to substitute the images we are using for Builders/Breakers/Defenders?

Like:
- ![Builders](https://img.shields.io/badge/OWASP-Builders-green): https://img.shields.io/badge/OWASP-Builders-green
- ![Defenders](https://img.shields.io/badge/OWASP-Defenders-blue): https://img.shields.io/badge/OWASP-Defenders-blue
- ![Breakers](https://img.shields.io/badge/OWASP-Breakers-red): https://img.shields.io/badge/OWASP-Breakers-red

They can be themed even:
- ![Builders](https://img.shields.io/badge/OWASP-Builders-green?style=for-the-badge)
- ![Builders](https://img.shields.io/badge/OWASP-Builders-green?style=flat)
- ![Builders](https://img.shields.io/badge/OWASP-Builders-green?style=flat-square)
- ![Builders](https://img.shields.io/badge/OWASP-Builders-green?style=flat-plastic)

See https://shields.io/category/other. Colors can be similar to the others, but those seem very distinctive.

I guess the easiest way is to have some jekyll plugin available in the base theme. And projects can just include them as: `{% badge breakers %}` or something equivalent...

I know the images were migrated to SVG in #9. But they seem sooo 2008. :smile:

**Comment by fzipi** [comment]
We can even ask shields to create a base badge for us! https://github.com/badges/shields/issues

**Comment by fzipi** [comment]
Seems we are going with font awesome now.

**Comment by kingthorin** [comment]
![OWASP Incubator](https://img.shields.io/badge/owasp-incubator-blue.svg)
![OWASP Lab](https://img.shields.io/badge/owasp-lab-yellow.svg)
![OWASP Flagship](https://img.shields.io/badge/owasp-flagship-green.svg)
