### ISSUE TITLE
tab_files.md does not appear as new tabs

### ISSUE THREAD

**Issue by oritro** [OWASP/www--site-theme#47]
In our project when adding a new tab_file.md file the main tab appear and that is it, no other tabs.
![image](https://user-images.githubusercontent.com/2639182/73210100-3f19ca80-4152-11ea-8303-cb80ae7ab825.png)
The content of the tab appears as hidden tab in the html page itself
`<section id="sec-meetings" class="page-body tab-hidden">`

project: https://github.com/OWASP/www-chapter-israel
will appreciate any feedback 

Ori

**Comment by hblankenship** [comment]
One of the tags in the tab files must match (case as well) a tag in the index.md file.  I recommend using the tag 'Israel' in both tab files.

**Comment by oritro** [comment]
thanks!
