### ISSUE TITLE
Search Button Firefox Issue

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www--site-theme#49]
The search button is always fully or partially obscured on Firefox. In fact the first number of times I saw it I thought it was some weird orphaned letter "C". Until recently when I browsed the site in Chrome.

![image](https://user-images.githubusercontent.com/7570458/74270144-be71d700-4cd8-11ea-83d0-63d5565801ea.png)

**Comment by hblankenship** [comment]
Any chance you are zoomed in?  I am not seeing that in Firefox on my
system.  How about screen resolution?

-

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by kingthorin** [comment]
Zero zoom, and OS Level "Change the size of text, apps, and other items" left at 100%, res is: 1920x1080 with Firefox window maximized.

Just adjusted to 1280x1024 and it persists.

Also disabled uBlock Origin so ensure it wasn't impacting things.

**Comment by hblankenship** [comment]
Hrmm  1920x1080 is also my res.

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by hblankenship** [comment]
I committed #40, please verify the fix worked for your case?

**Comment by kingthorin** [comment]
Thanks, yes that seems to have done it.
![image](https://user-images.githubusercontent.com/7570458/74947123-64ec6500-53c8-11ea-9957-c8b952a66137.png)

**Comment by kingthorin** [comment]
Well it's positioned properly if you are at the top of the screen but when you scroll it travels with you.

![image](https://user-images.githubusercontent.com/7570458/74954540-42ab1500-53d1-11ea-94bc-50440905315c.png)

**Comment by hblankenship** [comment]
Try it now

**Comment by kingthorin** [comment]
I think you've got it, thanks!
