### ISSUE TITLE
Donate button does not show on mobile

### ISSUE THREAD

**Issue by nanzggits** [OWASP/www--site-theme#51]
As per title, the donate button is not showing on mobile and it also doesn’t show in Firefox responsive mode (for testing purposes).

**Comment by kingthorin** [comment]
Is there a plan to address/fix this?

**Comment by bkimminich** [comment]
Maybe the donate button could be prioritized over the GitHub badges on small screens? Or just make it an icon only square button on mobile.

**Comment by bkimminich** [comment]
Currently it seems to be moved into the menu as a "Make a Donation" menu item only.

**Comment by hblankenship** [comment]
Yes, it was added as Make a Donation to the menu.
