### ISSUE TITLE
Using URL fragments causes pages to render empty

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www--site-theme#61]
No fragment:
https://owasp.org/www-project-web-security-testing-guide/
![image](https://user-images.githubusercontent.com/7570458/83763817-2319be80-a647-11ea-84f0-d5365d947d9b.png)

With fragment:
https://owasp.org/www-project-web-security-testing-guide/#stable
![image](https://user-images.githubusercontent.com/7570458/83763891-3a58ac00-a647-11ea-8067-ee7b58668360.png)

**Comment by kingthorin** [comment]
Note: 
https://owasp.org/www-project-web-security-testing-guide/index.html#stable
https://owasp.org/www-project-web-security-testing-guide/index#stable

Aren't any better.

**Comment by kingthorin** [comment]
Tested in latest Chrome and Firefox, haven't bothered with IE/Edge.

**Comment by hblankenship** [comment]
Give this a go.  I believe it should be working provided that the repository in question is rebuilt against the updated site theme (which WSTG was re-built by me to test this).  It may also require a refresh due to caching.

**Comment by kingthorin** [comment]
Seems to work, thanks!

https://owasp.org/www-project-web-security-testing-guide/#how-to-reference-wstg-scenarios

Just in-case anyone come across this later, of course it only works for the primary tab but I think that's fine for the majority of use cases.
