### ISSUE TITLE
Direct links to tabs always send you to last tab

### ISSUE THREAD

**Issue by bkimminich** [OWASP/www--site-theme#62]
### All these links...

* https://owasp.org/www-project-juice-shop/#div-main
* https://owasp.org/www-project-juice-shop/#div-features
* ...
* https://owasp.org/www-project-juice-shop/#div-ecosystem

### ...end up rendering

https://owasp.org/www-project-juice-shop/#div-supporters

_This messes with deep links already published and this wasn't always failing like this. This is not a Juice Shop specific problem, it also happens on other pages, e.g. https://owasp.org/www-project-dependency-track/#div-main ends up rendering https://owasp.org/www-project-dependency-track/#div-supporters._

**Comment by hblankenship** [comment]
Should be resolved on the next build cycle which is happening now.

**Comment by kingthorin** [comment]
@bkimminich can you confirm whether or not this is working once again?
