### ISSUE TITLE
Fix or Drop silly browser identification JS/Banner

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www--site-theme#64]
No owasp.org actually I'm running Firefox 78.0.1!!!!

![image](https://user-images.githubusercontent.com/7570458/86855269-00d0f180-c088-11ea-9a4f-9bed63a65ea3.png)

This seems to be another thing that suggests we need a testing plan/mechanism 👍

**Comment by bkimminich** [comment]
It can identify IE10, though... https://www.browserling.com/browse/win/7/ie/10/http%3A%2F%2Fowasp.org 😁

**Comment by hblankenship** [comment]
So very passionate.... The item that does that is javascript from browser-update.org.  Personally, I would think we could remove it entirely because, if you are using an old browser, you should already know that your mileage my vary.  Thought?

**Comment by kingthorin** [comment]
While it might be nice of us to suggest upgrades, it is even somewhat topical to the mission etc. If the component can't do it accurately then it seems to me more of a detractor than value add.

Plus I suspect the majority of visitors (as you suggested) will be aware that their browser of choice has limitations/support weaknesses.

Also I kinda wonder about the conversipn/action rate on such banners. Does anyone do anything other than hit ignore and try to continue anyway?

**Comment by hblankenship** [comment]
removed browser update js.  please note that it will take some time to propagate to all repos.
