### ISSUE TITLE
chapter_events.html include is broken?

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www--site-theme#71]
So OWASP seems to have this component that is recommend for chapter use to include their Meetup details. Which is indeed used by a few chapters and others are looking into it (per Slack discussions). However it seems that the infrastructure that facilitates the functionality is down or broken. Specifically the include leverages, for example:
https://owaspadmin.azurewebsites.net/api/GetMeetupEvents?code=7OIbdfrvam1q5dbaZyN5JTZodrtWRHtnzBTtRB8ed1HT2Stax0iLNw==&group=OWASP-Uruguay-Chapter

Which if accessed directly produces:
![image](https://user-images.githubusercontent.com/7570458/90580664-6a6c1180-e197-11ea-9c29-cd25b75cdac9.png)

When accessed as part of a chapter page on which it's used:
![image](https://user-images.githubusercontent.com/7570458/90580837-d3ec2000-e197-11ea-87b4-e56ce2ac9a83.png)

Per: https://github.com/search?q=chapter_events.html+filename%3Aindex.md this is used by 3 chapters, and the template repo. Plus at least one other chapter has asked about it on the Global slack.

Components such as this piece which is hosted in azure should likely have some sort of up/down or operational monitoring and alerting in place.

**Comment by hblankenship** [comment]
I have this fixed.  I agree about the monitoring.  We have some monitoring on other resources and even some within the azure resources but they need a better implementation.  I'll put that on the list.

**Comment by kingthorin** [comment]
Thanks @hblankenship

**Comment by martinmarsicano** [comment]
Now it's working, thank you @kingthorin and @hblankenship .
