### ISSUE TITLE
Allow override of default GitHub buttons

### ISSUE THREAD

**Issue by bkimminich** [OWASP/www--site-theme#8]
Right now each page shows the "Likes" and "Followers" of the website repository, e.g. for Juice Shop that of https://github.com/OWASP/www-project-juice-shop:

![image](https://user-images.githubusercontent.com/3531020/66820125-61d7f880-ef40-11e9-9630-03bc672775e4.png)

It would be better to introduce a new optional Jekyll variable like `github` which can be set to the project/chapter main repository URL. For Juice Shop that would be https://github.com/bkimminich/juice-shop and yield a much more impressive:

![image](https://user-images.githubusercontent.com/3531020/66820395-e0cd3100-ef40-11e9-8294-fe1f738cb34c.png)

The GitHub buttons should use this URL and fall back to the website repo if `github` is not specified.

**Comment by kingthorin** [comment]
How can we help make this happen?

**Comment by bkimminich** [comment]
I'm not good with the inner workings of Jekyll, but it should be nothing more than:
1. Introduce a page (or better: site) variable like `githubCodeRepo`
2. Change https://github.com/OWASP/www--site-theme/blob/f96e48e2d2196e6a4640d732f21373ab48b0b63d/_layouts/col-sidebar.html#L34-L35 so that this `githubCodeRepo` is used when it exists...
3. ...but otherwise the page repo is used

**Comment by kingthorin** [comment]
@hblankenship could we do it like this? (If so I'll open a PR)

```html
 <div class="github-buttons">
  <iframe src="https://ghbtns.com/github-btn.html?user=owasp&repo={{ site.github.code_repo | default: site.github.repository_name }}&type=star&count=true" frameborder="0" scrolling="0" width="170px" height="20px"></iframe>
  <iframe src="https://ghbtns.com/github-btn.html?user=owasp&repo={{ site.github.code_repo | default: site.github.repository_name }}&type=watch&count=true&v=2" frameborder="0" scrolling="0" width="170px" height="20px"></iframe>
</div>
```

**Comment by hblankenship** [comment]
Sounds good.  Please do open a PR.

-

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects
