### ISSUE TITLE
The site menu has European chapters split between EU and “Eastern Europe” but the chapters list has only “Europe” region

### ISSUE THREAD

**Issue by sainaen** [OWASP/www--site-theme#87]
In 8419bdc, the single `Europe` region has been split into two: `European Union` and `Eastern Europe`. But [`chapters.json` in the main site](https://github.com/OWASP/owasp.github.io/blob/main/_data/chapters.json) uses a single `Europe` region for European chapters.

Because of this, the site menu just opens the list of chapters without navigating to the linked section. Is this split — something which is being worked on right now and just hasn’t propagated to the chapters list?

**Comment by sainaen** [comment]
Also, I wonder where would UK chapters fit in this scheme?

**Comment by hblankenship** [comment]
Thanks for the feedback. The regions changed but it requires the chapters or a committee member or a staff member to also change the regions in their pages to the supported regions. It is a work in progress. I could eliminate displaying 'incorrect' regions on the chapters page but then the chapters would not show up at all. I may spend some time working on a more automated solution shortly just to get it resolved as it has been nearly 8 months with no movement on the issue.

**Comment by sainaen** [comment]
Oh, I see. Thank you!

I guess with 45e4587 the issue is now resolved. :tada:
